version: '3.1'
services:
  flask:
    build: .
    entrypoint: ["gunicorn", "-w1", "--reload", "--timeout=60", "-b:5000", "--access-logfile=-", "--error-logfile=-", "app:app"]
    # restart: unless-stopped
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - ${DIR}./app:/flask/app
      - ${DIR}./templates:/flask/templates
      - ${DIR}./profile:/flask/profile
